### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by shawn412** [Exunys/AirHub-V2#6]
if i execute it its not working

**Comment by Exunys** [comment]
I need more details such as what executor you used, what platform (PC or Mobile), any error messages...???

**Comment by dvrk666** [comment]
just nothing happens when executed via solara

**Comment by Exunys** [comment]
I fixed any Solara problems. Refer to: https://github.com/Exunys/AirHub-V2/issues/7

Enjoy using AirHub V2 ❤️ !
